// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TransactionKind string

const (
	TransactionKindIncome       TransactionKind = "income"
	TransactionKindExpense      TransactionKind = "expense"
	TransactionKindFixedExpense TransactionKind = "fixed_expense"
)

func (e *TransactionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionKind(s)
	case string:
		*e = TransactionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionKind: %T", src)
	}
	return nil
}

type NullTransactionKind struct {
	TransactionKind TransactionKind
	Valid           bool // Valid is true if TransactionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionKind) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionKind), nil
}

type Category struct {
	ID   int32
	Name string
	Kind string
}

type Currency struct {
	Code   string
	Name   string
	Symbol pgtype.Text
}

type Transaction struct {
	ID           int32
	UserID       int64
	Kind         TransactionKind
	Amount       pgtype.Numeric
	CurrencyCode string
	CategoryID   pgtype.Int8
	Description  pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
}
