// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
        user_id,
        kind,
        amount,
        currency_code,
        category_id,
        description
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, kind, amount, currency_code, category_id, description, created_at
`

type CreateTransactionParams struct {
	UserID       int64
	Kind         TransactionKind
	Amount       pgtype.Numeric
	CurrencyCode string
	CategoryID   pgtype.Int8
	Description  pgtype.Text
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Kind,
		arg.Amount,
		arg.CurrencyCode,
		arg.CategoryID,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Amount,
		&i.CurrencyCode,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAllUserTransactions = `-- name: GetAllUserTransactions :many
SELECT id, user_id, kind, amount, currency_code, category_id, description, created_at
FROM transactions
WHERE user_id = $1
`

func (q *Queries) GetAllUserTransactions(ctx context.Context, userID int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getAllUserTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Amount,
			&i.CurrencyCode,
			&i.CategoryID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
